apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  type: NodePort
  ports:
    - port: 8761
      name: port1
      protocol: TCP
      targetPort: 8761
      nodePort: 31000
  selector:
    app: eureka-server
