eureka:
  client:
    region: region-3
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://localhost:8761/eureka
    availability-zones:
      region-3: zone1
server:
  port: 8400
spring:
  application:
    name: cv-service
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cv_db
  datasource:
    url: jdbc:mariadb://localhost:3307/db_cv
    username: root
    password: 1234567890
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
