eureka:
  instance:
    prefer-ip-address: true
  client:
    region: region-5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://eureka-server:8761/eureka
    availability-zones:
      region-5: zone1
server:
  port: 8300
spring:
  application:
    name: jobs-user-service