eureka:
  client:
    region: region-5
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://localhost:8761/eureka
    availability-zones:
      region-5: zone1
server:
  port: 8300
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/db_jobuser
    username: root
    password: 1234567890
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: jobs-user-service