
eureka:
  instance:
    prefer-ip-address: true

  client:
    region: region-1
    register-with-eureka: true
    fetch-registry: true
    service-url:
      zone1: http://eureka-server:8761/eureka
#      zone1: http://localhost:8761/eureka
    availability-zones:
      region-1: zone1
server:
  port: 8100
spring:
  datasource:
    url: jdbc:mariadb://172.20.0.10:3307/db_account
#    url: jdbc:mariadb://localhost:3307/db_account
    username: root
    password: 1234567890
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: account-service
#value:
#  jwtSecret: jwtNVDAT1102
#  jwtExpiratio: 86400