apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  # labels:
  #   app: account-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      name: account-service
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: account-service:0.1
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8100